/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaSwing.Vuelo;

import edu.usal.controlador.consola.ControladorAerolinea;
import edu.usal.controlador.consola.ControladorVuelo;
import edu.usal.domain.Aerolinea;
import edu.usal.domain.Aeropuerto;
import edu.usal.domain.Vuelo;

import java.awt.*;
import java.util.List;

/**
 *
 * @author fservidio
 */
public class ModificarVuelo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarVuelo
     */
    public ModificarVuelo() {
        initComponents();
        this.PopulateAerolineas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        dateFechaSalidaVuelo = new com.toedter.calendar.JDateChooser();
        dateFechaLlegadaVuelo = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboBoxTipoVuelo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboBoxAerolineaVuelo = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Vuelo");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tiempo de Vuelo:");

        jLabel7.setText("Fecha y Hora de Llegada:");

        jLabel6.setText("Fecha y Hora de Salida:");

        jLabel5.setText("Aeropuerto de Llegada:");

        jLabel4.setText("Aeropuerto de salida:");

        jLabel3.setText("Cantidad de asientos:");

        jLabel2.setText("Numero de Vuelo:");

        jLabel1.setText("Ingresar ID de Vuelo a Modificar");

        jLabel9.setText("ID:");

        jButton2.setText("Ver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo de Vuelo:");

        comboBoxTipoVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Way" }));

        jLabel11.setText("Aerolinea:");

        comboBoxAerolineaVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboBoxAerolineaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAerolineaVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(dateFechaLlegadaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxTipoVuelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxAerolineaVuelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateFechaSalidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jTextField1))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dateFechaSalidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateFechaLlegadaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboBoxTipoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboBoxAerolineaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BOTON MODIFICAR.
        this.HandleConsultarVuelo();
    }//GEN-LAST:event_jButton2ActionPerformed



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(consulta != null) {
            this.HandleEditVuelo(consulta);
        } else {
            this.ShowAlerta("No se pude editar un vuelo sin consultarlo primero!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxAerolineaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAerolineaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxAerolineaVueloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxAerolineaVuelo;
    private javax.swing.JComboBox<String> comboBoxTipoVuelo;
    private com.toedter.calendar.JDateChooser dateFechaLlegadaVuelo;
    private com.toedter.calendar.JDateChooser dateFechaSalidaVuelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    // ----------------------------------------------------- = ------------------------------------------------------

    //Declaro mis objetos
    ControladorVuelo controlador = new ControladorVuelo();
    ControladorAerolinea controladorAerolinea = new ControladorAerolinea();
    List<Aerolinea> aerolineasList =  this.controladorAerolinea.ListadodeAerolinea();
    Vuelo consulta = new Vuelo();
    PopupMenu alerta;

    //Y mis metodos de manejo.

    //Metodo para traer datos de consulta.
    private void HandleConsultarVuelo() {
        try{
            int busqueda = Integer.parseInt(this.jTextField8.getText());
            consulta = new Vuelo();
            consulta.setIDVuelo(busqueda);
        } catch (Exception e){
            this.ShowAlerta("El Id tiene que ser un valor numerico!");
            e.printStackTrace();
        }
        try {
            consulta = this.controlador.ConsultadeVuelo(consulta);
            this.jTextField1.setText(consulta.getNumeroVuelo());
            this.jTextField2.setText(String.valueOf(consulta.getCantAsientos()));
            this.jTextField3.setText(consulta.getAeropuertodeSalida().getCodigodeAeropuerto());
            this.jTextField4.setText(consulta.getAeropuertodeLLegada().getCodigodeAeropuerto());
            this.dateFechaSalidaVuelo.setDate(consulta.getFechaSalida());
            this.dateFechaLlegadaVuelo.setDate(consulta.getFechaLLegada());
            this.jTextField7.setText(consulta.getTiempovuelo());
        } catch (Exception e){
            this.ShowAlerta("No se ha podido encontrar el vuelo, porfavor consulte la consola!");
        }
    }

    private void ShowAlerta(String mensaje){
        alerta = new PopupMenu();
        alerta.add(mensaje);
        this.jPanel1.add(alerta);
        alerta.show(jPanel1,0,0);
    }

    private void HandleEditVuelo(Vuelo alta){
        //Instancio Aeropuertos
        Aeropuerto salida;
        Aeropuerto llegada;

        boolean valido = true;

        //Mapeo el vuelo en cuestion.
        //Numero de vuelo
        if (this.HandleNumeroVuelo(this.jTextField1.getText())) {
            alta.setNumeroVuelo(this.jTextField1.getText());
        } else {
            valido = false;
            this.ShowAlerta("El numero de vuelo no puede estar vacio!");
        }

        //Asientos
        if(!this.jTextField2.getText().equals("")){
            alta.setCantAsientos(Integer.parseInt(this.jTextField2.getText()));
        } else {
            valido = false;
            this.ShowAlerta("La cantidad de asientos no puede ser dejada vacia!");
        }
        //Valido Aeropuerto de Salida
        if(this.HandleAeropuerto(this.jTextField3.getText())){
            salida = new Aeropuerto();
            salida.setCodigodeAeropuerto(this.jTextField3.getText());
            alta.setAeropuertodeSalida(salida);
        }
        //Valido Aeropuerto de Llegada
        if(this.HandleAeropuerto(this.jTextField4.getText())){
            llegada = new Aeropuerto();
            llegada.setCodigodeAeropuerto(this.jTextField4.getText());
            alta.setAeropuertodeLLegada(llegada);
        }
        //Valido dates de salida y llegada.
        if(this.dateFechaLlegadaVuelo.getDate() != null || this.dateFechaSalidaVuelo.getDate() != null){
            alta.setFechaLLegada(this.dateFechaLlegadaVuelo.getDate());
            alta.setFechaSalida(this.dateFechaSalidaVuelo.getDate());
        } else {
            valido = false;
            this.ShowAlerta("El vuelo tiene que tener fecha de Llegada y salida!");
        }

        alta.setTiempovuelo(this.jTextField7.getText());
        alta.setAerolinea(this.HandleAerolineaSelected());

        if (valido){
            if(this.controlador.ModificaciondeVuelo(alta)){
                this.ShowAlerta("Se guardo el vuelo de forma correcta!");
            } else {
                this.ShowAlerta("No se pudo guardar el vuelo, consulte la consola!");
            }
        }



    }


    private Aerolinea HandleAerolineaSelected() {

        for (Aerolinea a: aerolineasList) {
            if (a.getNombreAereoLinea().equals(this.comboBoxAerolineaVuelo.getSelectedItem().toString())){
                return a;
            }
        }
        return null;
    }

    //Metodo para validar los caracteres de Aeropuerto/Vuelo
    private boolean HandleAeropuerto(String aeropuerto) {
        if(aeropuerto.length() == 3){
            return true;
        } else {
            this.ShowAlerta("Error, el Aeropuerto solo puede seguir un codigo de 3 letras!" +
                    "\n EJ: EZE");
            return false;
        }
    }

    //Metodo para Popular la lista de Aerolineas del combobox.
    private void PopulateAerolineas(){
        for (Aerolinea a: aerolineasList) {
            this.comboBoxAerolineaVuelo.addItem(a.getNombreAereoLinea());
        }
    }

    //Metodo para generar el numero del vuelo correspondiente.
    private boolean HandleNumeroVuelo(String numerodevuelo) {
        try{
            int validar = Integer.parseInt(numerodevuelo);
            if(numerodevuelo.length() == 4){
                return true;
            } else {
                this.ShowAlerta("El numero de vuelo debe estar compuesto de 4 numeros!");
            }
        } catch (Exception e){
            this.ShowAlerta("Para editar el numero de vuelo se deben ingresar 4 nuevos numeros!");
            e.printStackTrace();
            return false;
        }
        return false;
    }
}
