/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaSwing.Venta;

import edu.usal.controlador.consola.ControladorVenta;
import edu.usal.domain.TipoPago;
import edu.usal.domain.Venta;

import java.awt.*;

/**
 *
 * @author fservidio
 */
public class ModificarVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarVentas
     */
    public ModificarVenta() {
        initComponents();
        this.PopulateTiposPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        comboBoxFormaDePagoModificarVenta = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboBoxCuotasModificarVenta = new javax.swing.JComboBox<>();
        btnGuardarModificarVenta = new javax.swing.JButton();
        btnVerModificarVenta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Venta");

        jLabel1.setText("Ingresa ID de Venta a Modificar");

        jLabel3.setText("ID:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel17.setText("Fecha y Hora de Venta:");

        jLabel18.setText("Forma de Pago:");

        comboBoxFormaDePagoModificarVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboBoxFormaDePagoModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFormaDePagoModificarVentaActionPerformed(evt);
            }
        });

        jLabel14.setText("Precio:");

        jLabel15.setText("Cuotas:");
        jLabel15.setVisible(false);

        comboBoxCuotasModificarVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"3","6","12","24"}));
        comboBoxCuotasModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCuotasModificarVentaActionPerformed(evt);
            }
        });
        comboBoxCuotasModificarVenta.setVisible(false);

        btnGuardarModificarVenta.setText("Guardar");
        btnGuardarModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificarVentaActionPerformed(evt);
            }
        });

        btnVerModificarVenta.setText("Ver");
        btnVerModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerModificarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(196, 196, 196))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerModificarVenta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnGuardarModificarVenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel18)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboBoxCuotasModificarVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField10)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(comboBoxFormaDePagoModificarVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(139, 139, 139)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerModificarVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(btnGuardarModificarVenta)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(comboBoxFormaDePagoModificarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxCuotasModificarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnVerModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerModificarVentaActionPerformed
        this.HandleConsultarVuelo();
    }//GEN-LAST:event_btnVerModificarVentaActionPerformed

    private void btnGuardarModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificarVentaActionPerformed
        if(consulta != null) {
            this.HandleModificarVenta(consulta);
        } else {
            this.ShowAlerta("No se pude editar un vuelo sin consultarlo primero!");
        }
    }//GEN-LAST:event_btnGuardarModificarVentaActionPerformed

    private void comboBoxFormaDePagoModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFormaDePagoModificarVentaActionPerformed
        this.HandleSelectedFormaDepago();
    }//GEN-LAST:event_comboBoxFormaDePagoModificarVentaActionPerformed

    private void comboBoxCuotasModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCuotasModificarVentaActionPerformed
        this.HandleCantidadDeCuotas();
    }//GEN-LAST:event_comboBoxCuotasModificarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarModificarVenta;
    private javax.swing.JButton btnVerModificarVenta;
    private javax.swing.JComboBox<String> comboBoxCuotasModificarVenta;
    private javax.swing.JComboBox<String> comboBoxFormaDePagoModificarVenta;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    // ----------------------------------------------------- = ------------------------------------------------------

    //Declaro mis objetos
    ControladorVenta controlador = new ControladorVenta();
    Venta consulta;
    PopupMenu alerta;


    //Y mis metodos de manejo.

    private void ShowAlerta(String mensaje){
        alerta = new PopupMenu();
        alerta.add(mensaje);
        this.jPanel1.add(alerta);
        alerta.show(jPanel1,0,0);
    }

    //Handlers

    //Handler de consulta
    private void HandleConsultarVuelo(){
        this.comboBoxCuotasModificarVenta.setVisible(false);
        this.jLabel15.setVisible(false);
        try{
            int busqueda = Integer.parseInt(this.jTextField6.getText());
            consulta = new Venta();
            consulta.setIDVenta(busqueda);
        } catch (Exception e){
            this.ShowAlerta("El Id tiene que ser un valor numerico!");
            e.printStackTrace();
        }
        try {
            consulta = this.controlador.ConsultadeVenta(consulta);
            this.jDateChooser1.setDate(consulta.getFecha_HS_Venta());
            this.comboBoxFormaDePagoModificarVenta.setSelectedItem(consulta.getFormadePago());
            if(consulta.getFormadePago().equals("Tarjeta de Credito")){
                this.comboBoxCuotasModificarVenta.setSelectedItem(consulta.getCuotas());
                this.comboBoxCuotasModificarVenta.setVisible(true);
                this.jLabel15.setVisible(true);
            }
            this.jTextField10.setText(consulta.getPrecio());
        } catch (Exception e){
            this.ShowAlerta("No se ha podido encontrar la venta, porfavor consulte la consola!");
        }
    }

    //Handler de guardado.
    private void HandleModificarVenta(Venta venta){
        boolean valido = true;

        venta.setFecha_HS_Venta(this.jDateChooser1.getDate());
        if(venta.getFecha_HS_Venta() == null){
            this.ShowAlerta("Se tiene que seleccionar una fecha para el vuelo!");
            valido = false;
        }

        venta.setFormadePago(this.comboBoxFormaDePagoModificarVenta.getSelectedItem().toString());

        if(venta.getFormadePago().equals("Tarjeta de Credito")){
            venta.setCuotas(this.comboBoxCuotasModificarVenta.getSelectedItem().toString());
        }

        if(!this.jTextField10.getText().equals("")){
            try{
                int precio = Integer.parseInt(this.jTextField10.getText());
                venta.setPrecio(String.valueOf(precio));
            } catch (Exception e){
                this.ShowAlerta("Error, el precio debe ser un valor numerico!");
                valido = false;
            }
        } else{
            this.ShowAlerta("El precio no se puede dejar vacio!");
            valido = false;
        }

        if (valido) {
            if ((this.controlador.ModificaciondeVenta(venta))) {
                this.ShowAlerta("Se pudo modificar la venta de forma correcta!");
            } else {
                this.ShowAlerta("No se pudo modificar la venta!");
            }
        }

    }

    //Metodo para popular los tipos de pago!
    private void PopulateTiposPago() {
        this.comboBoxFormaDePagoModificarVenta.addItem(TipoPago.getPago("Efectivo"));
        this.comboBoxFormaDePagoModificarVenta.addItem(TipoPago.getPago("Credito"));
        this.comboBoxFormaDePagoModificarVenta.addItem(TipoPago.getPago("Debito"));
    }

    //Metodo para manejar la forma seleccionada de pago.
    private void HandleSelectedFormaDepago(){
        if(this.comboBoxFormaDePagoModificarVenta.getSelectedItem().toString().equals("Efectivo")){
            this.comboBoxCuotasModificarVenta.setVisible(false);
            this.jLabel15.setVisible(false);
        }
        if(this.comboBoxFormaDePagoModificarVenta.getSelectedItem().toString().equals("Tarjeta de Debito")){
            this.comboBoxCuotasModificarVenta.setVisible(false);
            this.jLabel15.setVisible(false);
        }
        if(this.comboBoxFormaDePagoModificarVenta.getSelectedItem().toString().equals("Tarjeta de Credito")){
            this.comboBoxCuotasModificarVenta.setVisible(true);
            this.jLabel15.setVisible(true);
        }
    }

    //Metodo para manejar la cantidad de cuotas/El interes si es aplicable!
    private void HandleCantidadDeCuotas(){
        if(!this.jTextField10.getText().equals("")){
            try{
                int precio = Integer.parseInt(this.jTextField10.getText());
                if(this.comboBoxCuotasModificarVenta.getSelectedItem().toString().equals("12") ||
                        this.comboBoxCuotasModificarVenta.getSelectedItem().toString().equals("24")){
                    precio = precio+(precio*10)/100;
                    this.jTextField10.setText(Integer.toString(precio));
                }
            } catch (Exception e){
                this.ShowAlerta("Error, el precio debe ser un valor numerico!");
            }
        } else{
            this.comboBoxCuotasModificarVenta.setSelectedIndex(0);
            this.ShowAlerta("El precio debe ser ingresado primero!");
        }
    }
}
