/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaSwing;

import edu.usal.util.ConexionSQLServer;
import edu.usal.vista.consola.VISTAGENERAL;
import vistaSwing.Aerolinea.EliminarAerolinea;
import vistaSwing.Aerolinea.ModificarAerolinea;
import vistaSwing.Aerolinea.NuevaAerolinea;
import vistaSwing.Aerolinea.VerAerolineas;
import vistaSwing.Cliente.EliminarCliente;
import vistaSwing.Cliente.ModificarCliente;
import vistaSwing.Cliente.NuevoCliente;
import vistaSwing.Cliente.VerClientes;
import vistaSwing.Venta.EliminarVenta;
import vistaSwing.Venta.ModificarVenta;
import vistaSwing.Venta.NuevaVenta;
import vistaSwing.Venta.VerVentas;
import vistaSwing.Vuelo.EliminarVuelo;
import vistaSwing.Vuelo.ModificarVuelo;
import vistaSwing.Vuelo.NuevoVuelo;
import vistaSwing.Vuelo.VerVuelos;

/**
 *
 * @author fservidio
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenu3 = new javax.swing.JMenu();
        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opNuevoCliente = new javax.swing.JMenuItem();
        opVerClientes = new javax.swing.JMenuItem();
        opEliminarCliente = new javax.swing.JMenuItem();
        opModificarCliente = new javax.swing.JMenuItem();
        JMenu2 = new javax.swing.JMenu();
        opNuevaAerolinea = new javax.swing.JMenuItem();
        opVerAerolinea = new javax.swing.JMenuItem();
        opEliminarAerolinea = new javax.swing.JMenuItem();
        opModificarAerolinea = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        opNuevaVenta = new javax.swing.JMenuItem();
        opVerVentas = new javax.swing.JMenuItem();
        opEliminarVenta = new javax.swing.JMenuItem();
        opModificarVenta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        opNuevoVuelo = new javax.swing.JMenuItem();
        opVerVuelos = new javax.swing.JMenuItem();
        opEliminarVuelo = new javax.swing.JMenuItem();
        opModificarVuelo = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1372, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );

        jMenu1.setText("Cliente");

        opNuevoCliente.setText("Nuevo Cliente");
        opNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNuevoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opNuevoCliente);

        opVerClientes.setText("Ver Clientes");
        opVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVerClientesActionPerformed(evt);
            }
        });
        jMenu1.add(opVerClientes);

        opEliminarCliente.setText("Eliminar Cliente");
        opEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opEliminarCliente);

        opModificarCliente.setText("Modificar Cliente");
        opModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opModificarCliente);

        jMenuBar1.add(jMenu1);

        JMenu2.setText("Aerolinea");

        opNuevaAerolinea.setText("Nueva Aerolinea");
        opNuevaAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNuevaAerolineaActionPerformed(evt);
            }
        });
        JMenu2.add(opNuevaAerolinea);

        opVerAerolinea.setText("Ver Aerolineas");
        opVerAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVerAerolineaActionPerformed(evt);
            }
        });
        JMenu2.add(opVerAerolinea);

        opEliminarAerolinea.setText("Eliminar Aerolinea");
        opEliminarAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarAerolineaActionPerformed(evt);
            }
        });
        JMenu2.add(opEliminarAerolinea);

        opModificarAerolinea.setText("Modificar Aerolinea");
        opModificarAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarAerolineaActionPerformed(evt);
            }
        });
        JMenu2.add(opModificarAerolinea);

        jMenuBar1.add(JMenu2);

        jMenu4.setText("Venta");

        opNuevaVenta.setText("Nueva Venta");
        opNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNuevaVentaActionPerformed(evt);
            }
        });
        jMenu4.add(opNuevaVenta);

        opVerVentas.setText("Ver Ventas");
        opVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVerVentasActionPerformed(evt);
            }
        });
        jMenu4.add(opVerVentas);

        opEliminarVenta.setText("Eliminar Venta");
        opEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarVentaActionPerformed(evt);
            }
        });
        jMenu4.add(opEliminarVenta);

        opModificarVenta.setText("Modificar Venta");
        opModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarVentaActionPerformed(evt);
            }
        });
        jMenu4.add(opModificarVenta);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Vuelo");

        opNuevoVuelo.setText("Nuevo Vuelo");
        opNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNuevoVueloActionPerformed(evt);
            }
        });
        jMenu5.add(opNuevoVuelo);

        opVerVuelos.setText("Ver Vuelos");
        opVerVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVerVuelosActionPerformed(evt);
            }
        });
        jMenu5.add(opVerVuelos);

        opEliminarVuelo.setText("Eliminar Vuelo");
        opEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarVueloActionPerformed(evt);
            }
        });
        jMenu5.add(opEliminarVuelo);

        opModificarVuelo.setText("Modificar Vuelo");
        opModificarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarVueloActionPerformed(evt);
            }
        });
        jMenu5.add(opModificarVuelo);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNuevoClienteActionPerformed
        NuevoCliente nuevoCliente = new NuevoCliente();
        escritorio.add(nuevoCliente);
        nuevoCliente.show();
        
    }//GEN-LAST:event_opNuevoClienteActionPerformed

    private void opVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVerClientesActionPerformed
        VerClientes verClientes = new VerClientes();
        escritorio.add(verClientes);
        verClientes.show();
        
    }//GEN-LAST:event_opVerClientesActionPerformed

    private void opEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarClienteActionPerformed
        EliminarCliente eliminarCliente = new EliminarCliente();
        escritorio.add(eliminarCliente);
        eliminarCliente.show();
        
    }//GEN-LAST:event_opEliminarClienteActionPerformed

    private void opModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarClienteActionPerformed
        ModificarCliente modificarCliente = new ModificarCliente();
        escritorio.add(modificarCliente);
        modificarCliente.show();
    }//GEN-LAST:event_opModificarClienteActionPerformed

    private void opNuevaAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNuevaAerolineaActionPerformed
        NuevaAerolinea nuevaAerolinea = new NuevaAerolinea();
        escritorio.add(nuevaAerolinea);
        nuevaAerolinea.show();
    }//GEN-LAST:event_opNuevaAerolineaActionPerformed

    private void opVerAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVerAerolineaActionPerformed
        VerAerolineas verAerolineas = new VerAerolineas();
        escritorio.add(verAerolineas);
        verAerolineas.show();
    }//GEN-LAST:event_opVerAerolineaActionPerformed

    private void opEliminarAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarAerolineaActionPerformed
        EliminarAerolinea eliminarAerolinea = new EliminarAerolinea();
        escritorio.add(eliminarAerolinea);
        eliminarAerolinea.show();
    }//GEN-LAST:event_opEliminarAerolineaActionPerformed

    private void opModificarAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarAerolineaActionPerformed
        ModificarAerolinea modificarAerolinea = new ModificarAerolinea();
        escritorio.add(modificarAerolinea);
        modificarAerolinea.show();
    }//GEN-LAST:event_opModificarAerolineaActionPerformed

    private void opNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNuevaVentaActionPerformed
        NuevaVenta nuevaVenta = new NuevaVenta();
        escritorio.add(nuevaVenta);
        nuevaVenta.show();
    }//GEN-LAST:event_opNuevaVentaActionPerformed

    private void opVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVerVentasActionPerformed
        VerVentas verVentas = new VerVentas();
        escritorio.add(verVentas);
        verVentas.show();
    }//GEN-LAST:event_opVerVentasActionPerformed

    private void opEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarVentaActionPerformed
        EliminarVenta eliminarVenta = new EliminarVenta();
        escritorio.add(eliminarVenta);
        eliminarVenta.show();
    }//GEN-LAST:event_opEliminarVentaActionPerformed

    private void opModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarVentaActionPerformed
        ModificarVenta modificarVenta = new ModificarVenta();
        escritorio.add(modificarVenta);
        modificarVenta.show();
    }//GEN-LAST:event_opModificarVentaActionPerformed

    private void opNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNuevoVueloActionPerformed
        NuevoVuelo nuevoVuelo = new NuevoVuelo();
        escritorio.add(nuevoVuelo);
        nuevoVuelo.show();
    }//GEN-LAST:event_opNuevoVueloActionPerformed

    private void opVerVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVerVuelosActionPerformed
        VerVuelos verVuelos = new VerVuelos();
        escritorio.add(verVuelos);
        verVuelos.show();
    }//GEN-LAST:event_opVerVuelosActionPerformed

    private void opEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarVueloActionPerformed
        EliminarVuelo eliminarVuelo = new EliminarVuelo();
        escritorio.add(eliminarVuelo);
        eliminarVuelo.show();
    }//GEN-LAST:event_opEliminarVueloActionPerformed

    private void opModificarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarVueloActionPerformed
        ModificarVuelo modificarVuelo = new ModificarVuelo();
        escritorio.add(modificarVuelo);
        modificarVuelo.show();
    }//GEN-LAST:event_opModificarVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //Trato de hacer la conexion a la base de datos primero.
        if (ConexionSQLServer.ConnectToSqlDatabase() != null) {
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainMenu().setVisible(true);
                }
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu2;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem opEliminarAerolinea;
    private javax.swing.JMenuItem opEliminarCliente;
    private javax.swing.JMenuItem opEliminarVenta;
    private javax.swing.JMenuItem opEliminarVuelo;
    private javax.swing.JMenuItem opModificarAerolinea;
    private javax.swing.JMenuItem opModificarCliente;
    private javax.swing.JMenuItem opModificarVenta;
    private javax.swing.JMenuItem opModificarVuelo;
    private javax.swing.JMenuItem opNuevaAerolinea;
    private javax.swing.JMenuItem opNuevaVenta;
    private javax.swing.JMenuItem opNuevoCliente;
    private javax.swing.JMenuItem opNuevoVuelo;
    private javax.swing.JMenuItem opVerAerolinea;
    private javax.swing.JMenuItem opVerClientes;
    private javax.swing.JMenuItem opVerVentas;
    private javax.swing.JMenuItem opVerVuelos;
    // End of variables declaration//GEN-END:variables
}
